### ISSUE TITLE
ansible - iterate over list

### ISSUE THREAD

**Issue by o-lenczyk** [NowackiMichal/gcp-010-VM-users#1]
when coping user public keys, you do need to repeat same task many times, you can use something like this:

```
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"
```
    
  described here http://minimum-viable-automation.com/ansible/use-ansible-create-user-accounts-setup-ssh-keys/
